version: '3'

services:
  database:
    container_name: db
    build:
      context: .
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=opala
    ports:
      - "5432:5432"
